#ifndef MODEL_GLOBAL_H
#define MODEL_GLOBAL_H

#if defined(CATHIA_MODEL_LIBRARY)
#  define CATHIA_MODEL_EXPORT Q_DECL_EXPORT
#else
#  define CATHIA_MODEL_EXPORT Q_DECL_IMPORT
#endif

#endif // MODEL_GLOBAL_H
